# TrajectoryPlannerROS:
DWAPlannerROS:

  holonomic_robot: false
  sim_time: 1.0
  # .8 worked  well
  #vth_sample: 40
  #vx_sample: 20
  #vy_sample: 0
  path_distance_bias: 7.5
  goal_distance_bias: 2.0
  #occdist_scale: 1.5
  #trans_stopped_vel: 0.0
  #min_trans_vel: 0.0
  #max_trans_vel: .5
  #forward_point_distance: 0.0
  #max_vel_x: 0.5
  min_vel_x: 0.0
  #use_dwa: true
  
  
  
  
  
  
