map_type: costmap

obstacle_range: 7.5
raytrace_range: 10.0
footprint: [[-0.2, 0.1], [-0.1, 0.20], [0.1, 0.20], [0.2, 0.1], [0.2, -0.1], [0.1,-0.20], [-0.1, -0.20], [-0.2, -0.1]]

transform_tolerance: .3

inflation_radius: 1.0
cost_scaling_factor: 10

observation_sources: laser_scan_sensor


laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true, expected_update_rate: 0.15}
